services:
  db:
    image: mysql:8.0
    container_name: mysql_calendar_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: calendar_db
      MYSQL_USER: bot_user
      MYSQL_PASSWORD: bot_password
      MYSQL_ROOT_PASSWORD: root_strong_password
      TZ: Europe/Moscow # Время МСК для базы данных
    ports:
      - "3306:3306"
    volumes:
      # Папка на VPS для хранения данных базы (чтобы они не стирались)
      - mysql_data:/var/lib/mysql
      # Автоматическое выполнение скрипта инициализации таблиц
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 256M

  bot:
    build: .
    container_name: ts_calendar_bot
    restart: unless-stopped
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN} # Замените на ваш токен от BotFather
      DB_HOST: db
      DB_USER: bot_user
      DB_PASSWORD: bot_password
      DB_NAME: calendar_db

    # Добавляем веб-сервер, который сам заберет SSL-сертификат
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80" # Для проверки сертификатов Let's Encrypt
      - "443:443" # Для защищенных запросов от React-приложения
      - "81:81" # Панель управления Nginx (замените на свой порт или закройте потом)
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - bot

volumes:
  mysql_data:
